addr=$1

rm -f *.move
rm -f *.mv
rm -f *.mv.1
cp /home/ops/lmf/exchange-matchengine/violas_move/*.move ./

sed -i "s/7257c2417e4d1038e1817c8f283ace2e/$addr/g" *.move

../move-build bank.move -s 0x$addr -d /home/ops/lmf/move/stdlib/modules/signer.move /home/ops/lmf/move/stdlib/modules/libra_time.move /home/ops/lmf/move/stdlib/modules/libra_version.move /home/ops/lmf/move/stdlib/modules/testnet.move /home/ops/lmf/move/stdlib/modules/libra_configs.move /home/ops/lmf/move/stdlib/modules/account_limits.move /home/ops/lmf/move/stdlib/modules/sliding_nonce.move /home/ops/lmf/move/stdlib/modules/authenticator.move /home/ops/lmf/move/stdlib/modules/vector.move /home/ops/lmf/move/stdlib/modules/hash.move /home/ops/lmf/move/stdlib/modules/coin1.move /home/ops/lmf/move/stdlib/modules/empty.move /home/ops/lmf/move/stdlib/modules/compare.move /home/ops/lmf/move/stdlib/modules/transaction.move /home/ops/lmf/move/stdlib/modules/lbr.move /home/ops/lmf/move/stdlib/modules/lcs.move /home/ops/lmf/move/stdlib/modules/coin2.move /home/ops/lmf/move/stdlib/modules/offer.move /home/ops/lmf/move/stdlib/modules/transaction_fee.move /home/ops/lmf/move/stdlib/modules/fixedpoint32.move /home/ops/lmf/move/stdlib/modules/libra_account.move /home/ops/lmf/move/stdlib/modules/libra_transaction_timeout.move /home/ops/lmf/move/stdlib/modules/libra_writeset_manager.move /home/ops/lmf/move/stdlib/modules/registered_currencies.move /home/ops/lmf/move/stdlib/modules/association.move /home/ops/lmf/move/stdlib/modules/shared_ed25519_public_key.move /home/ops/lmf/move/stdlib/modules/event.move /home/ops/lmf/move/stdlib/modules/option.move /home/ops/lmf/move/stdlib/modules/debug.move /home/ops/lmf/move/stdlib/modules/signature.move /home/ops/lmf/move/stdlib/modules/genesis.move /home/ops/lmf/move/stdlib/modules/vasp.move /home/ops/lmf/move/stdlib/modules/libra_system.move /home/ops/lmf/move/stdlib/modules/libra_vm_config.move /home/ops/lmf/move/stdlib/modules/libra_block.move /home/ops/lmf/move/stdlib/modules/unhosted.move /home/ops/lmf/move/stdlib/modules/validator_config.move /home/ops/lmf/move/stdlib/modules/libra.move  

mv move_build_output/modules/0_ViolasBank.mv bank.mv 

../move-build publish.move -s 0x$addr -d /home/ops/lmf/move/stdlib/modules/signer.move /home/ops/lmf/move/stdlib/modules/libra_time.move /home/ops/lmf/move/stdlib/modules/libra_version.move /home/ops/lmf/move/stdlib/modules/testnet.move /home/ops/lmf/move/stdlib/modules/libra_configs.move /home/ops/lmf/move/stdlib/modules/account_limits.move /home/ops/lmf/move/stdlib/modules/sliding_nonce.move /home/ops/lmf/move/stdlib/modules/authenticator.move /home/ops/lmf/move/stdlib/modules/vector.move /home/ops/lmf/move/stdlib/modules/hash.move /home/ops/lmf/move/stdlib/modules/coin1.move /home/ops/lmf/move/stdlib/modules/empty.move /home/ops/lmf/move/stdlib/modules/compare.move /home/ops/lmf/move/stdlib/modules/transaction.move /home/ops/lmf/move/stdlib/modules/lbr.move /home/ops/lmf/move/stdlib/modules/lcs.move /home/ops/lmf/move/stdlib/modules/coin2.move /home/ops/lmf/move/stdlib/modules/offer.move /home/ops/lmf/move/stdlib/modules/transaction_fee.move /home/ops/lmf/move/stdlib/modules/fixedpoint32.move /home/ops/lmf/move/stdlib/modules/libra_account.move /home/ops/lmf/move/stdlib/modules/libra_transaction_timeout.move /home/ops/lmf/move/stdlib/modules/libra_writeset_manager.move /home/ops/lmf/move/stdlib/modules/registered_currencies.move /home/ops/lmf/move/stdlib/modules/association.move /home/ops/lmf/move/stdlib/modules/shared_ed25519_public_key.move /home/ops/lmf/move/stdlib/modules/event.move /home/ops/lmf/move/stdlib/modules/option.move /home/ops/lmf/move/stdlib/modules/debug.move /home/ops/lmf/move/stdlib/modules/signature.move /home/ops/lmf/move/stdlib/modules/genesis.move /home/ops/lmf/move/stdlib/modules/vasp.move /home/ops/lmf/move/stdlib/modules/libra_system.move /home/ops/lmf/move/stdlib/modules/libra_vm_config.move /home/ops/lmf/move/stdlib/modules/libra_block.move /home/ops/lmf/move/stdlib/modules/unhosted.move /home/ops/lmf/move/stdlib/modules/validator_config.move /home/ops/lmf/move/stdlib/modules/libra.move bank.move 

mv move_build_output/scripts/main.mv publish.mv 

../move-build register_libra_token.move -s 0x$addr -d /home/ops/lmf/move/stdlib/modules/signer.move /home/ops/lmf/move/stdlib/modules/libra_time.move /home/ops/lmf/move/stdlib/modules/libra_version.move /home/ops/lmf/move/stdlib/modules/testnet.move /home/ops/lmf/move/stdlib/modules/libra_configs.move /home/ops/lmf/move/stdlib/modules/account_limits.move /home/ops/lmf/move/stdlib/modules/sliding_nonce.move /home/ops/lmf/move/stdlib/modules/authenticator.move /home/ops/lmf/move/stdlib/modules/vector.move /home/ops/lmf/move/stdlib/modules/hash.move /home/ops/lmf/move/stdlib/modules/coin1.move /home/ops/lmf/move/stdlib/modules/empty.move /home/ops/lmf/move/stdlib/modules/compare.move /home/ops/lmf/move/stdlib/modules/transaction.move /home/ops/lmf/move/stdlib/modules/lbr.move /home/ops/lmf/move/stdlib/modules/lcs.move /home/ops/lmf/move/stdlib/modules/coin2.move /home/ops/lmf/move/stdlib/modules/offer.move /home/ops/lmf/move/stdlib/modules/transaction_fee.move /home/ops/lmf/move/stdlib/modules/fixedpoint32.move /home/ops/lmf/move/stdlib/modules/libra_account.move /home/ops/lmf/move/stdlib/modules/libra_transaction_timeout.move /home/ops/lmf/move/stdlib/modules/libra_writeset_manager.move /home/ops/lmf/move/stdlib/modules/registered_currencies.move /home/ops/lmf/move/stdlib/modules/association.move /home/ops/lmf/move/stdlib/modules/shared_ed25519_public_key.move /home/ops/lmf/move/stdlib/modules/event.move /home/ops/lmf/move/stdlib/modules/option.move /home/ops/lmf/move/stdlib/modules/debug.move /home/ops/lmf/move/stdlib/modules/signature.move /home/ops/lmf/move/stdlib/modules/genesis.move /home/ops/lmf/move/stdlib/modules/vasp.move /home/ops/lmf/move/stdlib/modules/libra_system.move /home/ops/lmf/move/stdlib/modules/libra_vm_config.move /home/ops/lmf/move/stdlib/modules/libra_block.move /home/ops/lmf/move/stdlib/modules/unhosted.move /home/ops/lmf/move/stdlib/modules/validator_config.move /home/ops/lmf/move/stdlib/modules/libra.move bank.move 

mv move_build_output/scripts/main.mv register_libra_token.mv 

../move-build enter_bank.move -s 0x$addr -d /home/ops/lmf/move/stdlib/modules/signer.move /home/ops/lmf/move/stdlib/modules/libra_time.move /home/ops/lmf/move/stdlib/modules/libra_version.move /home/ops/lmf/move/stdlib/modules/testnet.move /home/ops/lmf/move/stdlib/modules/libra_configs.move /home/ops/lmf/move/stdlib/modules/account_limits.move /home/ops/lmf/move/stdlib/modules/sliding_nonce.move /home/ops/lmf/move/stdlib/modules/authenticator.move /home/ops/lmf/move/stdlib/modules/vector.move /home/ops/lmf/move/stdlib/modules/hash.move /home/ops/lmf/move/stdlib/modules/coin1.move /home/ops/lmf/move/stdlib/modules/empty.move /home/ops/lmf/move/stdlib/modules/compare.move /home/ops/lmf/move/stdlib/modules/transaction.move /home/ops/lmf/move/stdlib/modules/lbr.move /home/ops/lmf/move/stdlib/modules/lcs.move /home/ops/lmf/move/stdlib/modules/coin2.move /home/ops/lmf/move/stdlib/modules/offer.move /home/ops/lmf/move/stdlib/modules/transaction_fee.move /home/ops/lmf/move/stdlib/modules/fixedpoint32.move /home/ops/lmf/move/stdlib/modules/libra_account.move /home/ops/lmf/move/stdlib/modules/libra_transaction_timeout.move /home/ops/lmf/move/stdlib/modules/libra_writeset_manager.move /home/ops/lmf/move/stdlib/modules/registered_currencies.move /home/ops/lmf/move/stdlib/modules/association.move /home/ops/lmf/move/stdlib/modules/shared_ed25519_public_key.move /home/ops/lmf/move/stdlib/modules/event.move /home/ops/lmf/move/stdlib/modules/option.move /home/ops/lmf/move/stdlib/modules/debug.move /home/ops/lmf/move/stdlib/modules/signature.move /home/ops/lmf/move/stdlib/modules/genesis.move /home/ops/lmf/move/stdlib/modules/vasp.move /home/ops/lmf/move/stdlib/modules/libra_system.move /home/ops/lmf/move/stdlib/modules/libra_vm_config.move /home/ops/lmf/move/stdlib/modules/libra_block.move /home/ops/lmf/move/stdlib/modules/unhosted.move /home/ops/lmf/move/stdlib/modules/validator_config.move /home/ops/lmf/move/stdlib/modules/libra.move bank.move 

mv move_build_output/scripts/main.mv enter_bank.mv 

../move-build exit_bank.move -s 0x$addr -d /home/ops/lmf/move/stdlib/modules/signer.move /home/ops/lmf/move/stdlib/modules/libra_time.move /home/ops/lmf/move/stdlib/modules/libra_version.move /home/ops/lmf/move/stdlib/modules/testnet.move /home/ops/lmf/move/stdlib/modules/libra_configs.move /home/ops/lmf/move/stdlib/modules/account_limits.move /home/ops/lmf/move/stdlib/modules/sliding_nonce.move /home/ops/lmf/move/stdlib/modules/authenticator.move /home/ops/lmf/move/stdlib/modules/vector.move /home/ops/lmf/move/stdlib/modules/hash.move /home/ops/lmf/move/stdlib/modules/coin1.move /home/ops/lmf/move/stdlib/modules/empty.move /home/ops/lmf/move/stdlib/modules/compare.move /home/ops/lmf/move/stdlib/modules/transaction.move /home/ops/lmf/move/stdlib/modules/lbr.move /home/ops/lmf/move/stdlib/modules/lcs.move /home/ops/lmf/move/stdlib/modules/coin2.move /home/ops/lmf/move/stdlib/modules/offer.move /home/ops/lmf/move/stdlib/modules/transaction_fee.move /home/ops/lmf/move/stdlib/modules/fixedpoint32.move /home/ops/lmf/move/stdlib/modules/libra_account.move /home/ops/lmf/move/stdlib/modules/libra_transaction_timeout.move /home/ops/lmf/move/stdlib/modules/libra_writeset_manager.move /home/ops/lmf/move/stdlib/modules/registered_currencies.move /home/ops/lmf/move/stdlib/modules/association.move /home/ops/lmf/move/stdlib/modules/shared_ed25519_public_key.move /home/ops/lmf/move/stdlib/modules/event.move /home/ops/lmf/move/stdlib/modules/option.move /home/ops/lmf/move/stdlib/modules/debug.move /home/ops/lmf/move/stdlib/modules/signature.move /home/ops/lmf/move/stdlib/modules/genesis.move /home/ops/lmf/move/stdlib/modules/vasp.move /home/ops/lmf/move/stdlib/modules/libra_system.move /home/ops/lmf/move/stdlib/modules/libra_vm_config.move /home/ops/lmf/move/stdlib/modules/libra_block.move /home/ops/lmf/move/stdlib/modules/unhosted.move /home/ops/lmf/move/stdlib/modules/validator_config.move /home/ops/lmf/move/stdlib/modules/libra.move bank.move 

mv move_build_output/scripts/main.mv exit_bank.mv 

../move-build update_price.move -s 0x$addr -d /home/ops/lmf/move/stdlib/modules/signer.move /home/ops/lmf/move/stdlib/modules/libra_time.move /home/ops/lmf/move/stdlib/modules/libra_version.move /home/ops/lmf/move/stdlib/modules/testnet.move /home/ops/lmf/move/stdlib/modules/libra_configs.move /home/ops/lmf/move/stdlib/modules/account_limits.move /home/ops/lmf/move/stdlib/modules/sliding_nonce.move /home/ops/lmf/move/stdlib/modules/authenticator.move /home/ops/lmf/move/stdlib/modules/vector.move /home/ops/lmf/move/stdlib/modules/hash.move /home/ops/lmf/move/stdlib/modules/coin1.move /home/ops/lmf/move/stdlib/modules/empty.move /home/ops/lmf/move/stdlib/modules/compare.move /home/ops/lmf/move/stdlib/modules/transaction.move /home/ops/lmf/move/stdlib/modules/lbr.move /home/ops/lmf/move/stdlib/modules/lcs.move /home/ops/lmf/move/stdlib/modules/coin2.move /home/ops/lmf/move/stdlib/modules/offer.move /home/ops/lmf/move/stdlib/modules/transaction_fee.move /home/ops/lmf/move/stdlib/modules/fixedpoint32.move /home/ops/lmf/move/stdlib/modules/libra_account.move /home/ops/lmf/move/stdlib/modules/libra_transaction_timeout.move /home/ops/lmf/move/stdlib/modules/libra_writeset_manager.move /home/ops/lmf/move/stdlib/modules/registered_currencies.move /home/ops/lmf/move/stdlib/modules/association.move /home/ops/lmf/move/stdlib/modules/shared_ed25519_public_key.move /home/ops/lmf/move/stdlib/modules/event.move /home/ops/lmf/move/stdlib/modules/option.move /home/ops/lmf/move/stdlib/modules/debug.move /home/ops/lmf/move/stdlib/modules/signature.move /home/ops/lmf/move/stdlib/modules/genesis.move /home/ops/lmf/move/stdlib/modules/vasp.move /home/ops/lmf/move/stdlib/modules/libra_system.move /home/ops/lmf/move/stdlib/modules/libra_vm_config.move /home/ops/lmf/move/stdlib/modules/libra_block.move /home/ops/lmf/move/stdlib/modules/unhosted.move /home/ops/lmf/move/stdlib/modules/validator_config.move /home/ops/lmf/move/stdlib/modules/libra.move bank.move 

mv move_build_output/scripts/main.mv update_price.mv 

../move-build update_collateral_factor.move -s 0x$addr -d /home/ops/lmf/move/stdlib/modules/signer.move /home/ops/lmf/move/stdlib/modules/libra_time.move /home/ops/lmf/move/stdlib/modules/libra_version.move /home/ops/lmf/move/stdlib/modules/testnet.move /home/ops/lmf/move/stdlib/modules/libra_configs.move /home/ops/lmf/move/stdlib/modules/account_limits.move /home/ops/lmf/move/stdlib/modules/sliding_nonce.move /home/ops/lmf/move/stdlib/modules/authenticator.move /home/ops/lmf/move/stdlib/modules/vector.move /home/ops/lmf/move/stdlib/modules/hash.move /home/ops/lmf/move/stdlib/modules/coin1.move /home/ops/lmf/move/stdlib/modules/empty.move /home/ops/lmf/move/stdlib/modules/compare.move /home/ops/lmf/move/stdlib/modules/transaction.move /home/ops/lmf/move/stdlib/modules/lbr.move /home/ops/lmf/move/stdlib/modules/lcs.move /home/ops/lmf/move/stdlib/modules/coin2.move /home/ops/lmf/move/stdlib/modules/offer.move /home/ops/lmf/move/stdlib/modules/transaction_fee.move /home/ops/lmf/move/stdlib/modules/fixedpoint32.move /home/ops/lmf/move/stdlib/modules/libra_account.move /home/ops/lmf/move/stdlib/modules/libra_transaction_timeout.move /home/ops/lmf/move/stdlib/modules/libra_writeset_manager.move /home/ops/lmf/move/stdlib/modules/registered_currencies.move /home/ops/lmf/move/stdlib/modules/association.move /home/ops/lmf/move/stdlib/modules/shared_ed25519_public_key.move /home/ops/lmf/move/stdlib/modules/event.move /home/ops/lmf/move/stdlib/modules/option.move /home/ops/lmf/move/stdlib/modules/debug.move /home/ops/lmf/move/stdlib/modules/signature.move /home/ops/lmf/move/stdlib/modules/genesis.move /home/ops/lmf/move/stdlib/modules/vasp.move /home/ops/lmf/move/stdlib/modules/libra_system.move /home/ops/lmf/move/stdlib/modules/libra_vm_config.move /home/ops/lmf/move/stdlib/modules/libra_block.move /home/ops/lmf/move/stdlib/modules/unhosted.move /home/ops/lmf/move/stdlib/modules/validator_config.move /home/ops/lmf/move/stdlib/modules/libra.move bank.move 

mv move_build_output/scripts/main.mv update_collateral_factor.mv 

../move-build lock.move -s 0x$addr -d /home/ops/lmf/move/stdlib/modules/signer.move /home/ops/lmf/move/stdlib/modules/libra_time.move /home/ops/lmf/move/stdlib/modules/libra_version.move /home/ops/lmf/move/stdlib/modules/testnet.move /home/ops/lmf/move/stdlib/modules/libra_configs.move /home/ops/lmf/move/stdlib/modules/account_limits.move /home/ops/lmf/move/stdlib/modules/sliding_nonce.move /home/ops/lmf/move/stdlib/modules/authenticator.move /home/ops/lmf/move/stdlib/modules/vector.move /home/ops/lmf/move/stdlib/modules/hash.move /home/ops/lmf/move/stdlib/modules/coin1.move /home/ops/lmf/move/stdlib/modules/empty.move /home/ops/lmf/move/stdlib/modules/compare.move /home/ops/lmf/move/stdlib/modules/transaction.move /home/ops/lmf/move/stdlib/modules/lbr.move /home/ops/lmf/move/stdlib/modules/lcs.move /home/ops/lmf/move/stdlib/modules/coin2.move /home/ops/lmf/move/stdlib/modules/offer.move /home/ops/lmf/move/stdlib/modules/transaction_fee.move /home/ops/lmf/move/stdlib/modules/fixedpoint32.move /home/ops/lmf/move/stdlib/modules/libra_account.move /home/ops/lmf/move/stdlib/modules/libra_transaction_timeout.move /home/ops/lmf/move/stdlib/modules/libra_writeset_manager.move /home/ops/lmf/move/stdlib/modules/registered_currencies.move /home/ops/lmf/move/stdlib/modules/association.move /home/ops/lmf/move/stdlib/modules/shared_ed25519_public_key.move /home/ops/lmf/move/stdlib/modules/event.move /home/ops/lmf/move/stdlib/modules/option.move /home/ops/lmf/move/stdlib/modules/debug.move /home/ops/lmf/move/stdlib/modules/signature.move /home/ops/lmf/move/stdlib/modules/genesis.move /home/ops/lmf/move/stdlib/modules/vasp.move /home/ops/lmf/move/stdlib/modules/libra_system.move /home/ops/lmf/move/stdlib/modules/libra_vm_config.move /home/ops/lmf/move/stdlib/modules/libra_block.move /home/ops/lmf/move/stdlib/modules/unhosted.move /home/ops/lmf/move/stdlib/modules/validator_config.move /home/ops/lmf/move/stdlib/modules/libra.move bank.move 

mv move_build_output/scripts/main.mv lock.mv 

../move-build redeem.move -s 0x$addr -d /home/ops/lmf/move/stdlib/modules/signer.move /home/ops/lmf/move/stdlib/modules/libra_time.move /home/ops/lmf/move/stdlib/modules/libra_version.move /home/ops/lmf/move/stdlib/modules/testnet.move /home/ops/lmf/move/stdlib/modules/libra_configs.move /home/ops/lmf/move/stdlib/modules/account_limits.move /home/ops/lmf/move/stdlib/modules/sliding_nonce.move /home/ops/lmf/move/stdlib/modules/authenticator.move /home/ops/lmf/move/stdlib/modules/vector.move /home/ops/lmf/move/stdlib/modules/hash.move /home/ops/lmf/move/stdlib/modules/coin1.move /home/ops/lmf/move/stdlib/modules/empty.move /home/ops/lmf/move/stdlib/modules/compare.move /home/ops/lmf/move/stdlib/modules/transaction.move /home/ops/lmf/move/stdlib/modules/lbr.move /home/ops/lmf/move/stdlib/modules/lcs.move /home/ops/lmf/move/stdlib/modules/coin2.move /home/ops/lmf/move/stdlib/modules/offer.move /home/ops/lmf/move/stdlib/modules/transaction_fee.move /home/ops/lmf/move/stdlib/modules/fixedpoint32.move /home/ops/lmf/move/stdlib/modules/libra_account.move /home/ops/lmf/move/stdlib/modules/libra_transaction_timeout.move /home/ops/lmf/move/stdlib/modules/libra_writeset_manager.move /home/ops/lmf/move/stdlib/modules/registered_currencies.move /home/ops/lmf/move/stdlib/modules/association.move /home/ops/lmf/move/stdlib/modules/shared_ed25519_public_key.move /home/ops/lmf/move/stdlib/modules/event.move /home/ops/lmf/move/stdlib/modules/option.move /home/ops/lmf/move/stdlib/modules/debug.move /home/ops/lmf/move/stdlib/modules/signature.move /home/ops/lmf/move/stdlib/modules/genesis.move /home/ops/lmf/move/stdlib/modules/vasp.move /home/ops/lmf/move/stdlib/modules/libra_system.move /home/ops/lmf/move/stdlib/modules/libra_vm_config.move /home/ops/lmf/move/stdlib/modules/libra_block.move /home/ops/lmf/move/stdlib/modules/unhosted.move /home/ops/lmf/move/stdlib/modules/validator_config.move /home/ops/lmf/move/stdlib/modules/libra.move bank.move 

mv move_build_output/scripts/main.mv redeem.mv 

../move-build borrow.move -s 0x$addr -d /home/ops/lmf/move/stdlib/modules/signer.move /home/ops/lmf/move/stdlib/modules/libra_time.move /home/ops/lmf/move/stdlib/modules/libra_version.move /home/ops/lmf/move/stdlib/modules/testnet.move /home/ops/lmf/move/stdlib/modules/libra_configs.move /home/ops/lmf/move/stdlib/modules/account_limits.move /home/ops/lmf/move/stdlib/modules/sliding_nonce.move /home/ops/lmf/move/stdlib/modules/authenticator.move /home/ops/lmf/move/stdlib/modules/vector.move /home/ops/lmf/move/stdlib/modules/hash.move /home/ops/lmf/move/stdlib/modules/coin1.move /home/ops/lmf/move/stdlib/modules/empty.move /home/ops/lmf/move/stdlib/modules/compare.move /home/ops/lmf/move/stdlib/modules/transaction.move /home/ops/lmf/move/stdlib/modules/lbr.move /home/ops/lmf/move/stdlib/modules/lcs.move /home/ops/lmf/move/stdlib/modules/coin2.move /home/ops/lmf/move/stdlib/modules/offer.move /home/ops/lmf/move/stdlib/modules/transaction_fee.move /home/ops/lmf/move/stdlib/modules/fixedpoint32.move /home/ops/lmf/move/stdlib/modules/libra_account.move /home/ops/lmf/move/stdlib/modules/libra_transaction_timeout.move /home/ops/lmf/move/stdlib/modules/libra_writeset_manager.move /home/ops/lmf/move/stdlib/modules/registered_currencies.move /home/ops/lmf/move/stdlib/modules/association.move /home/ops/lmf/move/stdlib/modules/shared_ed25519_public_key.move /home/ops/lmf/move/stdlib/modules/event.move /home/ops/lmf/move/stdlib/modules/option.move /home/ops/lmf/move/stdlib/modules/debug.move /home/ops/lmf/move/stdlib/modules/signature.move /home/ops/lmf/move/stdlib/modules/genesis.move /home/ops/lmf/move/stdlib/modules/vasp.move /home/ops/lmf/move/stdlib/modules/libra_system.move /home/ops/lmf/move/stdlib/modules/libra_vm_config.move /home/ops/lmf/move/stdlib/modules/libra_block.move /home/ops/lmf/move/stdlib/modules/unhosted.move /home/ops/lmf/move/stdlib/modules/validator_config.move /home/ops/lmf/move/stdlib/modules/libra.move bank.move 

mv move_build_output/scripts/main.mv borrow.mv 

../move-build repay_borrow.move -s 0x$addr -d /home/ops/lmf/move/stdlib/modules/signer.move /home/ops/lmf/move/stdlib/modules/libra_time.move /home/ops/lmf/move/stdlib/modules/libra_version.move /home/ops/lmf/move/stdlib/modules/testnet.move /home/ops/lmf/move/stdlib/modules/libra_configs.move /home/ops/lmf/move/stdlib/modules/account_limits.move /home/ops/lmf/move/stdlib/modules/sliding_nonce.move /home/ops/lmf/move/stdlib/modules/authenticator.move /home/ops/lmf/move/stdlib/modules/vector.move /home/ops/lmf/move/stdlib/modules/hash.move /home/ops/lmf/move/stdlib/modules/coin1.move /home/ops/lmf/move/stdlib/modules/empty.move /home/ops/lmf/move/stdlib/modules/compare.move /home/ops/lmf/move/stdlib/modules/transaction.move /home/ops/lmf/move/stdlib/modules/lbr.move /home/ops/lmf/move/stdlib/modules/lcs.move /home/ops/lmf/move/stdlib/modules/coin2.move /home/ops/lmf/move/stdlib/modules/offer.move /home/ops/lmf/move/stdlib/modules/transaction_fee.move /home/ops/lmf/move/stdlib/modules/fixedpoint32.move /home/ops/lmf/move/stdlib/modules/libra_account.move /home/ops/lmf/move/stdlib/modules/libra_transaction_timeout.move /home/ops/lmf/move/stdlib/modules/libra_writeset_manager.move /home/ops/lmf/move/stdlib/modules/registered_currencies.move /home/ops/lmf/move/stdlib/modules/association.move /home/ops/lmf/move/stdlib/modules/shared_ed25519_public_key.move /home/ops/lmf/move/stdlib/modules/event.move /home/ops/lmf/move/stdlib/modules/option.move /home/ops/lmf/move/stdlib/modules/debug.move /home/ops/lmf/move/stdlib/modules/signature.move /home/ops/lmf/move/stdlib/modules/genesis.move /home/ops/lmf/move/stdlib/modules/vasp.move /home/ops/lmf/move/stdlib/modules/libra_system.move /home/ops/lmf/move/stdlib/modules/libra_vm_config.move /home/ops/lmf/move/stdlib/modules/libra_block.move /home/ops/lmf/move/stdlib/modules/unhosted.move /home/ops/lmf/move/stdlib/modules/validator_config.move /home/ops/lmf/move/stdlib/modules/libra.move bank.move 

mv move_build_output/scripts/main.mv repay_borrow.mv 

../move-build liquidate_borrow.move -s 0x$addr -d /home/ops/lmf/move/stdlib/modules/signer.move /home/ops/lmf/move/stdlib/modules/libra_time.move /home/ops/lmf/move/stdlib/modules/libra_version.move /home/ops/lmf/move/stdlib/modules/testnet.move /home/ops/lmf/move/stdlib/modules/libra_configs.move /home/ops/lmf/move/stdlib/modules/account_limits.move /home/ops/lmf/move/stdlib/modules/sliding_nonce.move /home/ops/lmf/move/stdlib/modules/authenticator.move /home/ops/lmf/move/stdlib/modules/vector.move /home/ops/lmf/move/stdlib/modules/hash.move /home/ops/lmf/move/stdlib/modules/coin1.move /home/ops/lmf/move/stdlib/modules/empty.move /home/ops/lmf/move/stdlib/modules/compare.move /home/ops/lmf/move/stdlib/modules/transaction.move /home/ops/lmf/move/stdlib/modules/lbr.move /home/ops/lmf/move/stdlib/modules/lcs.move /home/ops/lmf/move/stdlib/modules/coin2.move /home/ops/lmf/move/stdlib/modules/offer.move /home/ops/lmf/move/stdlib/modules/transaction_fee.move /home/ops/lmf/move/stdlib/modules/fixedpoint32.move /home/ops/lmf/move/stdlib/modules/libra_account.move /home/ops/lmf/move/stdlib/modules/libra_transaction_timeout.move /home/ops/lmf/move/stdlib/modules/libra_writeset_manager.move /home/ops/lmf/move/stdlib/modules/registered_currencies.move /home/ops/lmf/move/stdlib/modules/association.move /home/ops/lmf/move/stdlib/modules/shared_ed25519_public_key.move /home/ops/lmf/move/stdlib/modules/event.move /home/ops/lmf/move/stdlib/modules/option.move /home/ops/lmf/move/stdlib/modules/debug.move /home/ops/lmf/move/stdlib/modules/signature.move /home/ops/lmf/move/stdlib/modules/genesis.move /home/ops/lmf/move/stdlib/modules/vasp.move /home/ops/lmf/move/stdlib/modules/libra_system.move /home/ops/lmf/move/stdlib/modules/libra_vm_config.move /home/ops/lmf/move/stdlib/modules/libra_block.move /home/ops/lmf/move/stdlib/modules/unhosted.move /home/ops/lmf/move/stdlib/modules/validator_config.move /home/ops/lmf/move/stdlib/modules/libra.move bank.move 

mv move_build_output/scripts/main.mv liquidate_borrow.mv 

../move-build create_token.move -s 0x$addr -d /home/ops/lmf/move/stdlib/modules/signer.move /home/ops/lmf/move/stdlib/modules/libra_time.move /home/ops/lmf/move/stdlib/modules/libra_version.move /home/ops/lmf/move/stdlib/modules/testnet.move /home/ops/lmf/move/stdlib/modules/libra_configs.move /home/ops/lmf/move/stdlib/modules/account_limits.move /home/ops/lmf/move/stdlib/modules/sliding_nonce.move /home/ops/lmf/move/stdlib/modules/authenticator.move /home/ops/lmf/move/stdlib/modules/vector.move /home/ops/lmf/move/stdlib/modules/hash.move /home/ops/lmf/move/stdlib/modules/coin1.move /home/ops/lmf/move/stdlib/modules/empty.move /home/ops/lmf/move/stdlib/modules/compare.move /home/ops/lmf/move/stdlib/modules/transaction.move /home/ops/lmf/move/stdlib/modules/lbr.move /home/ops/lmf/move/stdlib/modules/lcs.move /home/ops/lmf/move/stdlib/modules/coin2.move /home/ops/lmf/move/stdlib/modules/offer.move /home/ops/lmf/move/stdlib/modules/transaction_fee.move /home/ops/lmf/move/stdlib/modules/fixedpoint32.move /home/ops/lmf/move/stdlib/modules/libra_account.move /home/ops/lmf/move/stdlib/modules/libra_transaction_timeout.move /home/ops/lmf/move/stdlib/modules/libra_writeset_manager.move /home/ops/lmf/move/stdlib/modules/registered_currencies.move /home/ops/lmf/move/stdlib/modules/association.move /home/ops/lmf/move/stdlib/modules/shared_ed25519_public_key.move /home/ops/lmf/move/stdlib/modules/event.move /home/ops/lmf/move/stdlib/modules/option.move /home/ops/lmf/move/stdlib/modules/debug.move /home/ops/lmf/move/stdlib/modules/signature.move /home/ops/lmf/move/stdlib/modules/genesis.move /home/ops/lmf/move/stdlib/modules/vasp.move /home/ops/lmf/move/stdlib/modules/libra_system.move /home/ops/lmf/move/stdlib/modules/libra_vm_config.move /home/ops/lmf/move/stdlib/modules/libra_block.move /home/ops/lmf/move/stdlib/modules/unhosted.move /home/ops/lmf/move/stdlib/modules/validator_config.move /home/ops/lmf/move/stdlib/modules/libra.move bank.move 

mv move_build_output/scripts/main.mv create_token.mv 

../move-build update_price_index.move -s 0x$addr -d /home/ops/lmf/move/stdlib/modules/signer.move /home/ops/lmf/move/stdlib/modules/libra_time.move /home/ops/lmf/move/stdlib/modules/libra_version.move /home/ops/lmf/move/stdlib/modules/testnet.move /home/ops/lmf/move/stdlib/modules/libra_configs.move /home/ops/lmf/move/stdlib/modules/account_limits.move /home/ops/lmf/move/stdlib/modules/sliding_nonce.move /home/ops/lmf/move/stdlib/modules/authenticator.move /home/ops/lmf/move/stdlib/modules/vector.move /home/ops/lmf/move/stdlib/modules/hash.move /home/ops/lmf/move/stdlib/modules/coin1.move /home/ops/lmf/move/stdlib/modules/empty.move /home/ops/lmf/move/stdlib/modules/compare.move /home/ops/lmf/move/stdlib/modules/transaction.move /home/ops/lmf/move/stdlib/modules/lbr.move /home/ops/lmf/move/stdlib/modules/lcs.move /home/ops/lmf/move/stdlib/modules/coin2.move /home/ops/lmf/move/stdlib/modules/offer.move /home/ops/lmf/move/stdlib/modules/transaction_fee.move /home/ops/lmf/move/stdlib/modules/fixedpoint32.move /home/ops/lmf/move/stdlib/modules/libra_account.move /home/ops/lmf/move/stdlib/modules/libra_transaction_timeout.move /home/ops/lmf/move/stdlib/modules/libra_writeset_manager.move /home/ops/lmf/move/stdlib/modules/registered_currencies.move /home/ops/lmf/move/stdlib/modules/association.move /home/ops/lmf/move/stdlib/modules/shared_ed25519_public_key.move /home/ops/lmf/move/stdlib/modules/event.move /home/ops/lmf/move/stdlib/modules/option.move /home/ops/lmf/move/stdlib/modules/debug.move /home/ops/lmf/move/stdlib/modules/signature.move /home/ops/lmf/move/stdlib/modules/genesis.move /home/ops/lmf/move/stdlib/modules/vasp.move /home/ops/lmf/move/stdlib/modules/libra_system.move /home/ops/lmf/move/stdlib/modules/libra_vm_config.move /home/ops/lmf/move/stdlib/modules/libra_block.move /home/ops/lmf/move/stdlib/modules/unhosted.move /home/ops/lmf/move/stdlib/modules/validator_config.move /home/ops/lmf/move/stdlib/modules/libra.move bank.move 

mv move_build_output/scripts/main.mv update_price_index.mv 

../move-build mint.move -s 0x$addr -d /home/ops/lmf/move/stdlib/modules/signer.move /home/ops/lmf/move/stdlib/modules/libra_time.move /home/ops/lmf/move/stdlib/modules/libra_version.move /home/ops/lmf/move/stdlib/modules/testnet.move /home/ops/lmf/move/stdlib/modules/libra_configs.move /home/ops/lmf/move/stdlib/modules/account_limits.move /home/ops/lmf/move/stdlib/modules/sliding_nonce.move /home/ops/lmf/move/stdlib/modules/authenticator.move /home/ops/lmf/move/stdlib/modules/vector.move /home/ops/lmf/move/stdlib/modules/hash.move /home/ops/lmf/move/stdlib/modules/coin1.move /home/ops/lmf/move/stdlib/modules/empty.move /home/ops/lmf/move/stdlib/modules/compare.move /home/ops/lmf/move/stdlib/modules/transaction.move /home/ops/lmf/move/stdlib/modules/lbr.move /home/ops/lmf/move/stdlib/modules/lcs.move /home/ops/lmf/move/stdlib/modules/coin2.move /home/ops/lmf/move/stdlib/modules/offer.move /home/ops/lmf/move/stdlib/modules/transaction_fee.move /home/ops/lmf/move/stdlib/modules/fixedpoint32.move /home/ops/lmf/move/stdlib/modules/libra_account.move /home/ops/lmf/move/stdlib/modules/libra_transaction_timeout.move /home/ops/lmf/move/stdlib/modules/libra_writeset_manager.move /home/ops/lmf/move/stdlib/modules/registered_currencies.move /home/ops/lmf/move/stdlib/modules/association.move /home/ops/lmf/move/stdlib/modules/shared_ed25519_public_key.move /home/ops/lmf/move/stdlib/modules/event.move /home/ops/lmf/move/stdlib/modules/option.move /home/ops/lmf/move/stdlib/modules/debug.move /home/ops/lmf/move/stdlib/modules/signature.move /home/ops/lmf/move/stdlib/modules/genesis.move /home/ops/lmf/move/stdlib/modules/vasp.move /home/ops/lmf/move/stdlib/modules/libra_system.move /home/ops/lmf/move/stdlib/modules/libra_vm_config.move /home/ops/lmf/move/stdlib/modules/libra_block.move /home/ops/lmf/move/stdlib/modules/unhosted.move /home/ops/lmf/move/stdlib/modules/validator_config.move /home/ops/lmf/move/stdlib/modules/libra.move bank.move 

mv move_build_output/scripts/main.mv mint.mv 

../move-build lock_index.move -s 0x$addr -d /home/ops/lmf/move/stdlib/modules/signer.move /home/ops/lmf/move/stdlib/modules/libra_time.move /home/ops/lmf/move/stdlib/modules/libra_version.move /home/ops/lmf/move/stdlib/modules/testnet.move /home/ops/lmf/move/stdlib/modules/libra_configs.move /home/ops/lmf/move/stdlib/modules/account_limits.move /home/ops/lmf/move/stdlib/modules/sliding_nonce.move /home/ops/lmf/move/stdlib/modules/authenticator.move /home/ops/lmf/move/stdlib/modules/vector.move /home/ops/lmf/move/stdlib/modules/hash.move /home/ops/lmf/move/stdlib/modules/coin1.move /home/ops/lmf/move/stdlib/modules/empty.move /home/ops/lmf/move/stdlib/modules/compare.move /home/ops/lmf/move/stdlib/modules/transaction.move /home/ops/lmf/move/stdlib/modules/lbr.move /home/ops/lmf/move/stdlib/modules/lcs.move /home/ops/lmf/move/stdlib/modules/coin2.move /home/ops/lmf/move/stdlib/modules/offer.move /home/ops/lmf/move/stdlib/modules/transaction_fee.move /home/ops/lmf/move/stdlib/modules/fixedpoint32.move /home/ops/lmf/move/stdlib/modules/libra_account.move /home/ops/lmf/move/stdlib/modules/libra_transaction_timeout.move /home/ops/lmf/move/stdlib/modules/libra_writeset_manager.move /home/ops/lmf/move/stdlib/modules/registered_currencies.move /home/ops/lmf/move/stdlib/modules/association.move /home/ops/lmf/move/stdlib/modules/shared_ed25519_public_key.move /home/ops/lmf/move/stdlib/modules/event.move /home/ops/lmf/move/stdlib/modules/option.move /home/ops/lmf/move/stdlib/modules/debug.move /home/ops/lmf/move/stdlib/modules/signature.move /home/ops/lmf/move/stdlib/modules/genesis.move /home/ops/lmf/move/stdlib/modules/vasp.move /home/ops/lmf/move/stdlib/modules/libra_system.move /home/ops/lmf/move/stdlib/modules/libra_vm_config.move /home/ops/lmf/move/stdlib/modules/libra_block.move /home/ops/lmf/move/stdlib/modules/unhosted.move /home/ops/lmf/move/stdlib/modules/validator_config.move /home/ops/lmf/move/stdlib/modules/libra.move bank.move 

mv move_build_output/scripts/main.mv lock_index.mv 

../move-build redeem_index.move -s 0x$addr -d /home/ops/lmf/move/stdlib/modules/signer.move /home/ops/lmf/move/stdlib/modules/libra_time.move /home/ops/lmf/move/stdlib/modules/libra_version.move /home/ops/lmf/move/stdlib/modules/testnet.move /home/ops/lmf/move/stdlib/modules/libra_configs.move /home/ops/lmf/move/stdlib/modules/account_limits.move /home/ops/lmf/move/stdlib/modules/sliding_nonce.move /home/ops/lmf/move/stdlib/modules/authenticator.move /home/ops/lmf/move/stdlib/modules/vector.move /home/ops/lmf/move/stdlib/modules/hash.move /home/ops/lmf/move/stdlib/modules/coin1.move /home/ops/lmf/move/stdlib/modules/empty.move /home/ops/lmf/move/stdlib/modules/compare.move /home/ops/lmf/move/stdlib/modules/transaction.move /home/ops/lmf/move/stdlib/modules/lbr.move /home/ops/lmf/move/stdlib/modules/lcs.move /home/ops/lmf/move/stdlib/modules/coin2.move /home/ops/lmf/move/stdlib/modules/offer.move /home/ops/lmf/move/stdlib/modules/transaction_fee.move /home/ops/lmf/move/stdlib/modules/fixedpoint32.move /home/ops/lmf/move/stdlib/modules/libra_account.move /home/ops/lmf/move/stdlib/modules/libra_transaction_timeout.move /home/ops/lmf/move/stdlib/modules/libra_writeset_manager.move /home/ops/lmf/move/stdlib/modules/registered_currencies.move /home/ops/lmf/move/stdlib/modules/association.move /home/ops/lmf/move/stdlib/modules/shared_ed25519_public_key.move /home/ops/lmf/move/stdlib/modules/event.move /home/ops/lmf/move/stdlib/modules/option.move /home/ops/lmf/move/stdlib/modules/debug.move /home/ops/lmf/move/stdlib/modules/signature.move /home/ops/lmf/move/stdlib/modules/genesis.move /home/ops/lmf/move/stdlib/modules/vasp.move /home/ops/lmf/move/stdlib/modules/libra_system.move /home/ops/lmf/move/stdlib/modules/libra_vm_config.move /home/ops/lmf/move/stdlib/modules/libra_block.move /home/ops/lmf/move/stdlib/modules/unhosted.move /home/ops/lmf/move/stdlib/modules/validator_config.move /home/ops/lmf/move/stdlib/modules/libra.move bank.move 

mv move_build_output/scripts/main.mv redeem_index.mv 

../move-build borrow_index.move -s 0x$addr -d /home/ops/lmf/move/stdlib/modules/signer.move /home/ops/lmf/move/stdlib/modules/libra_time.move /home/ops/lmf/move/stdlib/modules/libra_version.move /home/ops/lmf/move/stdlib/modules/testnet.move /home/ops/lmf/move/stdlib/modules/libra_configs.move /home/ops/lmf/move/stdlib/modules/account_limits.move /home/ops/lmf/move/stdlib/modules/sliding_nonce.move /home/ops/lmf/move/stdlib/modules/authenticator.move /home/ops/lmf/move/stdlib/modules/vector.move /home/ops/lmf/move/stdlib/modules/hash.move /home/ops/lmf/move/stdlib/modules/coin1.move /home/ops/lmf/move/stdlib/modules/empty.move /home/ops/lmf/move/stdlib/modules/compare.move /home/ops/lmf/move/stdlib/modules/transaction.move /home/ops/lmf/move/stdlib/modules/lbr.move /home/ops/lmf/move/stdlib/modules/lcs.move /home/ops/lmf/move/stdlib/modules/coin2.move /home/ops/lmf/move/stdlib/modules/offer.move /home/ops/lmf/move/stdlib/modules/transaction_fee.move /home/ops/lmf/move/stdlib/modules/fixedpoint32.move /home/ops/lmf/move/stdlib/modules/libra_account.move /home/ops/lmf/move/stdlib/modules/libra_transaction_timeout.move /home/ops/lmf/move/stdlib/modules/libra_writeset_manager.move /home/ops/lmf/move/stdlib/modules/registered_currencies.move /home/ops/lmf/move/stdlib/modules/association.move /home/ops/lmf/move/stdlib/modules/shared_ed25519_public_key.move /home/ops/lmf/move/stdlib/modules/event.move /home/ops/lmf/move/stdlib/modules/option.move /home/ops/lmf/move/stdlib/modules/debug.move /home/ops/lmf/move/stdlib/modules/signature.move /home/ops/lmf/move/stdlib/modules/genesis.move /home/ops/lmf/move/stdlib/modules/vasp.move /home/ops/lmf/move/stdlib/modules/libra_system.move /home/ops/lmf/move/stdlib/modules/libra_vm_config.move /home/ops/lmf/move/stdlib/modules/libra_block.move /home/ops/lmf/move/stdlib/modules/unhosted.move /home/ops/lmf/move/stdlib/modules/validator_config.move /home/ops/lmf/move/stdlib/modules/libra.move bank.move 

mv move_build_output/scripts/main.mv borrow_index.mv 

../move-build repay_borrow_index.move -s 0x$addr -d /home/ops/lmf/move/stdlib/modules/signer.move /home/ops/lmf/move/stdlib/modules/libra_time.move /home/ops/lmf/move/stdlib/modules/libra_version.move /home/ops/lmf/move/stdlib/modules/testnet.move /home/ops/lmf/move/stdlib/modules/libra_configs.move /home/ops/lmf/move/stdlib/modules/account_limits.move /home/ops/lmf/move/stdlib/modules/sliding_nonce.move /home/ops/lmf/move/stdlib/modules/authenticator.move /home/ops/lmf/move/stdlib/modules/vector.move /home/ops/lmf/move/stdlib/modules/hash.move /home/ops/lmf/move/stdlib/modules/coin1.move /home/ops/lmf/move/stdlib/modules/empty.move /home/ops/lmf/move/stdlib/modules/compare.move /home/ops/lmf/move/stdlib/modules/transaction.move /home/ops/lmf/move/stdlib/modules/lbr.move /home/ops/lmf/move/stdlib/modules/lcs.move /home/ops/lmf/move/stdlib/modules/coin2.move /home/ops/lmf/move/stdlib/modules/offer.move /home/ops/lmf/move/stdlib/modules/transaction_fee.move /home/ops/lmf/move/stdlib/modules/fixedpoint32.move /home/ops/lmf/move/stdlib/modules/libra_account.move /home/ops/lmf/move/stdlib/modules/libra_transaction_timeout.move /home/ops/lmf/move/stdlib/modules/libra_writeset_manager.move /home/ops/lmf/move/stdlib/modules/registered_currencies.move /home/ops/lmf/move/stdlib/modules/association.move /home/ops/lmf/move/stdlib/modules/shared_ed25519_public_key.move /home/ops/lmf/move/stdlib/modules/event.move /home/ops/lmf/move/stdlib/modules/option.move /home/ops/lmf/move/stdlib/modules/debug.move /home/ops/lmf/move/stdlib/modules/signature.move /home/ops/lmf/move/stdlib/modules/genesis.move /home/ops/lmf/move/stdlib/modules/vasp.move /home/ops/lmf/move/stdlib/modules/libra_system.move /home/ops/lmf/move/stdlib/modules/libra_vm_config.move /home/ops/lmf/move/stdlib/modules/libra_block.move /home/ops/lmf/move/stdlib/modules/unhosted.move /home/ops/lmf/move/stdlib/modules/validator_config.move /home/ops/lmf/move/stdlib/modules/libra.move bank.move 

mv move_build_output/scripts/main.mv repay_borrow_index.mv 

../move-build liquidate_borrow_index.move -s 0x$addr -d /home/ops/lmf/move/stdlib/modules/signer.move /home/ops/lmf/move/stdlib/modules/libra_time.move /home/ops/lmf/move/stdlib/modules/libra_version.move /home/ops/lmf/move/stdlib/modules/testnet.move /home/ops/lmf/move/stdlib/modules/libra_configs.move /home/ops/lmf/move/stdlib/modules/account_limits.move /home/ops/lmf/move/stdlib/modules/sliding_nonce.move /home/ops/lmf/move/stdlib/modules/authenticator.move /home/ops/lmf/move/stdlib/modules/vector.move /home/ops/lmf/move/stdlib/modules/hash.move /home/ops/lmf/move/stdlib/modules/coin1.move /home/ops/lmf/move/stdlib/modules/empty.move /home/ops/lmf/move/stdlib/modules/compare.move /home/ops/lmf/move/stdlib/modules/transaction.move /home/ops/lmf/move/stdlib/modules/lbr.move /home/ops/lmf/move/stdlib/modules/lcs.move /home/ops/lmf/move/stdlib/modules/coin2.move /home/ops/lmf/move/stdlib/modules/offer.move /home/ops/lmf/move/stdlib/modules/transaction_fee.move /home/ops/lmf/move/stdlib/modules/fixedpoint32.move /home/ops/lmf/move/stdlib/modules/libra_account.move /home/ops/lmf/move/stdlib/modules/libra_transaction_timeout.move /home/ops/lmf/move/stdlib/modules/libra_writeset_manager.move /home/ops/lmf/move/stdlib/modules/registered_currencies.move /home/ops/lmf/move/stdlib/modules/association.move /home/ops/lmf/move/stdlib/modules/shared_ed25519_public_key.move /home/ops/lmf/move/stdlib/modules/event.move /home/ops/lmf/move/stdlib/modules/option.move /home/ops/lmf/move/stdlib/modules/debug.move /home/ops/lmf/move/stdlib/modules/signature.move /home/ops/lmf/move/stdlib/modules/genesis.move /home/ops/lmf/move/stdlib/modules/vasp.move /home/ops/lmf/move/stdlib/modules/libra_system.move /home/ops/lmf/move/stdlib/modules/libra_vm_config.move /home/ops/lmf/move/stdlib/modules/libra_block.move /home/ops/lmf/move/stdlib/modules/unhosted.move /home/ops/lmf/move/stdlib/modules/validator_config.move /home/ops/lmf/move/stdlib/modules/libra.move bank.move 

mv move_build_output/scripts/main.mv liquidate_borrow_index.mv 

